apiVersion: batch/v1
kind: Job
metadata:
  name: init-db-job
spec:
  template:
    spec:
      containers:
      - name: init-db
        image: ${REGISTRY}/init-db:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "scripts/init_db.py"]
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017"
      restartPolicy: OnFailure
  backoffLimit: 4
